---
elasticsearch__version: "5.6.14"
elasticsearch__jvm_heapsize: "2g"
elasticsearch__mem_limit: "4g"
opensearch__version: "2.3.0"
# elasticsearch__number_of_replicas: "0"
# defaults file for elasticsearch
