---
- name: Add repo file
  ansible.builtin.get_url:
    dest: "/etc/yum.repos.d/docker-ce.repo"
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    mode: "0644"
  tags:
    - install

- name: Install the docker compose plugin
  ansible.builtin.yum:
    name: docker-compose-plugin
    state: present
  tags:
    - install
