---
# - name: Get deb-file
#   ansible.builtin.get_url:
#     url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch__version }}.deb"
#     dest: /root
#     owner: root
#     group: root
#     mode: "0644"

- name: Install deb-file
  ansible.builtin.apt:
    # deb: "/root/elasticsearch-{{ elasticsearch__version }}.deb"
    deb: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch__version }}.deb"
