---
# - name: Install rabbitmq
#   ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Change or add JVM heap-size
  ansible.builtin.lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: "{{ item }}"
    backrefs: true
    line: '\g<1>4g'
  with_items:
    - '^(-Xmx)[1-9].*'
    - '^(-Xms)[1-9].*'

- name: Add ports
  ansible.builtin.lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: "{{ item }}"
  with_items:
    - "http.port: 9200"
    - "transport.port: 9300"

- name: Set kernel map-ccount
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_set: true
    state: present
    reload: true
# tasks file for elasticsearch
